name: photo_archiver
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  desktop_drop: ^0.6.1
  dropdown_button2: ^2.3.9
  ffi: ^2.1.4
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.3.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
